#!/bin/sh

#PBS -N spherical_cell

#PBS -M brbass@umich.edu
#PBS -m abe

#PBS -l nodes=1:ppn=2,pmem=25gb,walltime=8:00:00
#PBS -j oe
#PBS -V

#PBS -A bckiedro_fluxm
#PBS -q fluxm
#PBS -l qos=flux

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi

# set OpenMP environment
# export OMP_NUM_THREADS=2

#  Put your job commands here:
ibex test_5.xml &
ibex test_11.xml &
wait
