#!/bin/sh

#PBS -N icsbep_pu_generation

#PBS -M brbass@umich.edu
#PBS -m abe

#PBS -l nodes=1:ppn=4,pmem=4gb,walltime=72:00:00
#PBS -j oe
#PBS -V

#PBS -A bckiedro_flux
#PBS -q flux
#PBS -l qos=flux

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi

# set OpenMP environment
export OMP_NUM_THREADS=4

#  Put your job commands here:
python run.py

